# Generated by Django 4.2.11 on 2024-04-08 12:45

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[accounts.validators.phone_validator], verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
