# Generated by Django 4.2.11 on 2024-04-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us`s'},
        ),
    ]
