# Generated by Django 4.2.11 on 2024-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contactusmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Is Subscribed?')),
            ],
            options={
                'verbose_name': 'News letter',
                'verbose_name_plural': 'News letters',
            },
        ),
    ]
