# Generated by Django 4.2.11 on 2024-03-31 09:38

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[accounts.validators.national_code_validator]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[accounts.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[accounts.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[accounts.validators.phone_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Admin'), (4, 'Superuser')], default=1),
        ),
    ]
