# Generated by Django 4.2.11 on 2024-04-06 11:27

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(default='img2.jpg', upload_to=shop.models.image_path, verbose_name='Image'),
        ),
    ]
