# Generated by Django 4.2.11 on 2024-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='shop.categorymodel', verbose_name='Categories'),
        ),
    ]
