# Generated by Django 4.2.11 on 2024-04-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='shop.categorymodel', verbose_name='Categories'),
        ),
    ]
