# Generated by Django 4.2.11 on 2024-04-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='default/img4.jpg', upload_to='product/extra-img/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='ProductCategoryModel',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='/default/img4.jpg', upload_to='product/img/'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productmodel', verbose_name='Product'),
        ),
    ]
