# Generated by Django 4.2.11 on 2024-04-28 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='limit_usage',
            new_name='max_limit_usage',
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='couponmodel',
            name='used_by',
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
