# Generated by Django 4.2.11 on 2024-04-28 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_alter_orderitemmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
