# Generated by Django 4.2.11 on 2024-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'پرداخت شده'), (3, 'در حال پردازش'), (4, 'ارسال شده'), (5, 'تحویل داده شده'), (6, 'لغو شده')], default=1),
        ),
    ]
